// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSy-Tvyglvqe_nM92cM4RdSeO-m1m8pc4',
    appId: '1:1045127190992:web:d7d1e281f039e6c3b881d5',
    messagingSenderId: '1045127190992',
    projectId: 'physicalapp-7fd40',
    authDomain: 'physicalapp-7fd40.firebaseapp.com',
    storageBucket: 'physicalapp-7fd40.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuQBBP__fH7_zN74DBchC9dchP6rYI6S0',
    appId: '1:1045127190992:android:c96bbf1a3d16514ab881d5',
    messagingSenderId: '1045127190992',
    projectId: 'physicalapp-7fd40',
    storageBucket: 'physicalapp-7fd40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTSf6cuANJCZGL9t0f-ABYsWIRuzo_nns',
    appId: '1:1045127190992:ios:0f388bcf49f14a8fb881d5',
    messagingSenderId: '1045127190992',
    projectId: 'physicalapp-7fd40',
    storageBucket: 'physicalapp-7fd40.firebasestorage.app',
    iosBundleId: 'com.example.hp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTSf6cuANJCZGL9t0f-ABYsWIRuzo_nns',
    appId: '1:1045127190992:ios:0f388bcf49f14a8fb881d5',
    messagingSenderId: '1045127190992',
    projectId: 'physicalapp-7fd40',
    storageBucket: 'physicalapp-7fd40.firebasestorage.app',
    iosBundleId: 'com.example.hp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSy-Tvyglvqe_nM92cM4RdSeO-m1m8pc4',
    appId: '1:1045127190992:web:7225c4c1bca65a6bb881d5',
    messagingSenderId: '1045127190992',
    projectId: 'physicalapp-7fd40',
    authDomain: 'physicalapp-7fd40.firebaseapp.com',
    storageBucket: 'physicalapp-7fd40.firebasestorage.app',
  );
}
